// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefADbmaBED7Mbg6EmEAwfs_ha-WIP0Lo',
    appId: '1:51264775940:web:cb2ea2ab43b8a67d7bd251',
    messagingSenderId: '51264775940',
    projectId: 'ecommerce-fire-base',
    authDomain: 'ecommerce-fire-base.firebaseapp.com',
    storageBucket: 'ecommerce-fire-base.appspot.com',
    measurementId: 'G-RC9TMJCTQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8FRB0MTYbKbDXG91kCUD8UG1hS9htLA',
    appId: '1:51264775940:android:76acafaa139858d07bd251',
    messagingSenderId: '51264775940',
    projectId: 'ecommerce-fire-base',
    storageBucket: 'ecommerce-fire-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNnL-PZP52K68nSqZCL2p2vr-EiBM3Fkg',
    appId: '1:51264775940:ios:8499c2e8d89373087bd251',
    messagingSenderId: '51264775940',
    projectId: 'ecommerce-fire-base',
    storageBucket: 'ecommerce-fire-base.appspot.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNnL-PZP52K68nSqZCL2p2vr-EiBM3Fkg',
    appId: '1:51264775940:ios:8499c2e8d89373087bd251',
    messagingSenderId: '51264775940',
    projectId: 'ecommerce-fire-base',
    storageBucket: 'ecommerce-fire-base.appspot.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDefADbmaBED7Mbg6EmEAwfs_ha-WIP0Lo',
    appId: '1:51264775940:web:4f22ca335a75ee3a7bd251',
    messagingSenderId: '51264775940',
    projectId: 'ecommerce-fire-base',
    authDomain: 'ecommerce-fire-base.firebaseapp.com',
    storageBucket: 'ecommerce-fire-base.appspot.com',
    measurementId: 'G-TQWFRF1JDK',
  );
}
